### ISSUE TITLE
OAuth2.0 support

### ISSUE THREAD

**Issue by realZhangChi** [polterguy/magic#103]
Hi,
We already have an SSO server and would like to integrate it with Magic, but I haven't found anything useful in the documentation.
How to integrate our SSO into Magic?
Any help is appreciated. Thanks.

**Comment by polterguy** [comment]
Hi Zhang,

Hmmm, what _type_ of token is your OAuth2 server creating? If it's JWT, the simples would be to just share the token from your OAuth2 server with Magic through its `magic:auth:secret` configuration setting. Notice, this will _only_ work if you are using the same hashing algorithm as Magic is using, which I can't remember out of the back of my head.

Alternatively, how is your SSO built? Windows authentication? LDAP? If so, you can integrate AD and LDAP directly into Magic, completely bypassing the entire problem ...

The third (and most complex alternative) is to _"fork"_ the project called _"magic.lambda.auth"_ and build your own logic in here, that forwards the request to your OAuth2 server - Which shouldn't be _too_ difficult, but requires some manual work on your side. The advantage with this is that you don't have to change anything in magic itself, except replacing the _"magic.lambda.auth"_ project, and manually using the source code for _"magic.library"_, drop the standard _"magic.lambda.auth"_ and replace it with a project reference to your own version.

If you do this, you'll need to implement all the slots found in this project, and implement these using your own custom logic. It probably sounds daunting, but probably isn't that complex once you've found the rhythm ...

**Comment by polterguy** [comment]
Hi Zhang, sorry for answering erroneously, but I rarely visit these parts myself, so I intend to forget the exact semantics from time to time. First [read this](https://polterguy.github.io/tutorials/auth-internals/).

Then realise you can replace the username/password authentication mechanism in Magic by exchanging the slot invoked as Magic checks your username/password, as it does when you are authenticating. The parts that are interesting is the top parts, _before_ the _"Windows authentication"_ parts. The rest is only interesting if you're doing LDAP, which you're not.

Basically, modify your appSettings.json file as follows.

```
{
  "magic": {
    "auth": {
      "authentication": "acme.inc.oauth2.authenticate",
```

Then [read this](https://polterguy.github.io/documentation/magic.lambda/) - Specifically, scroll down to the _"Extending Hyperlambda"_ parts. And create a C# method as follows ...

```
using System.Linq;
using magic.node;
using magic.signals.contracts;

namespace acme.foo
{
    [Slot(Name = "acme.inc.oauth2.authenticate")]
    public class Foo : ISlot
    {
        public void Signal(ISignaler signaler, Node input)
        {
            var username = input.Children.First(x => x.Name == "username").Get<string>();
            var password = input.Children.First(x => x.Name == "password").Get<string>();

            // Invoke your OAuth provider here with the username and password
            // And if it succeeds (returns authentication) make sure your slot returns
            // true as follows
            input.Value = true;
        }
    }
}
```

And that's it :)
