### ISSUE TITLE
Error with epochs

### ISSUE THREAD

**Issue by Colandus** [polterguy/magic#218]
When attempting to train a model, I specified epochs manually and received this error:

`Additional properties are not allowed ('epochs' was unexpected)" type:invalid_request_error param code`

**Comment by polterguy** [comment]
Hmm, thank you, I'll try to figure this out.

May I ask what you're trying to create? As a general rule of thumb, you get 1,000 times better results by avoiding training but instead using _"Vectorise"_. This is also 99.8% less expensive ...

**Comment by Colandus** [comment]
I'm trying to create a support bot. I've scrapped our support website. I've never really messed with AI in general before, so I have little knowledge how it works and I'm not very familiar with any of the terms either. So I'm just learning slowly. I didn't know what vectorise was, tried to Google it with little success. If I understand you correctly, I shouldn't use the "Train" feature at all, but only Vectorise? Do you have any resource where I can read about how it works/what it is?

If I wanted to request/suggest features, should I do that as an issue?

**Comment by Colandus** [comment]
Tried the Vectorising but getting an error. No helpful description. I suppose I'm doing something wrong.

![bild](https://user-images.githubusercontent.com/6376212/216836971-472e3901-bbb1-4a84-9916-8b1ae34f5d2c.png)

**Comment by polterguy** [comment]
Great, how many pages does it create, or training snippets I guess? After craping your site, and changing to the _"Training data"_ tab, and filtering on your model's name. How many snippets did it generate?

I suggest you completely avoid training, and simply go to your model and click the _"Vectorise"_ part. Then you have to ensure your model has turned on *"Use vectors"* (click advanced while configuring model)

This part doesn't reinforce the underlaying model, but rather relies upon embeddings and typically gives you a 1,000 times better result. Let me know how many training snippets you've got, and if there's _another_ log item before the one you showed me ...

**Comment by Colandus** [comment]
I tried the vectorising and it gave me an error without a description. I posted it here but then realized there was another log informing me that I probably had run out of credit (was just using the free credit). So I removed that post. Not sure if you caught that post and are responding to it.

Either way, now I have about 2500 snippets. Lots of them are noise, but I thought I'd just let them be there and later on see if I can get a plain version of the site without any additional data besides what's needed for the scraping. My first tests was on another page and gave bad results using training (again with lots of noise which may have contributed partly to that). I'm going to try to vectorising again and make sure it's turned on on the model.

**Comment by polterguy** [comment]
Great! A piece of advice about _"noise / garbage data"_ is to start out by removing navigation stuff. These are typically the exact same _"prompt"_ and you can filter on them in your _"Training data"_ component, and simply click _"Delete all"_. This will delete all snippets you are currently filtering on. If you've got 200 pages, you've typically for 200 similar snippets, often several of these, since most sites unfortunately are using Hx elements in navbars, footers, headers, etc ...

Let me know when you've got things working :)

Psst ==> [watch this](https://www.youtube.com/watch?v=BBBDQd-mdGE)

**Comment by polterguy** [comment]
How is this thing going? Do you need more help?

**Comment by Colandus** [comment]
Hey! Thanks for asking. I haven't gotten around to test it yet as I'm doing this on my spare time. I'll have to make a version of the support site without the garbage data, then I'll be ready to test the vectorising!

You may close this issue if you wish.

**Comment by polterguy** [comment]
OK, great! Exactly my reasons for asking :)
