### ISSUE TITLE
no read, no write access on downloaded files?

### ISSUE THREAD

**Issue by j2l** [polterguy/magic#219]
Hello!
Great project, I love it :)

**Describe the bug**
After downloading and unziping the frontend, I noticed that all files have wrong rights: 
![image](https://user-images.githubusercontent.com/65325/219055040-589757e5-2b47-48d3-a1b6-a507b5d97ffc.png)

**To Reproduce**
1. Download fronted
2. unzip
3. check files

Easy fix is setting the folder permission and clicking the button  `Apply permissions to enclosed files` but I guess it'll annoy others too :)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04

**Comment by polterguy** [comment]
Thx mate, I thought ZIP files didn't include folder permissions? Am I missing something here ...?

**Comment by j2l** [comment]
I guess they are but I have no idea how to set them up, sorry.

You're in Cyprus? Καλημέρα! Or are you in the Turkish part?

**Comment by polterguy** [comment]
Kali mera mate ^_^

Nope, in Limassol :)

However, my Greek is roughly 50 words ...

**Comment by j2l** [comment]
When I click on download it's only zip
![image](https://user-images.githubusercontent.com/65325/219060943-0fa9bb94-5ee4-4a00-853c-86597014527a.png)

**Comment by polterguy** [comment]
Ahh, GET it! Yes, we don't have GZ/TAR support in the core, and I am 99% certain of that ZIP doesn't allow for providing file permissions, so it'll end up downloading _"in the context of your user"_ or something on Linux. I don't think this is a problem we can (easily) fix ... :/

Unless you want to have a go at it ofc ...

I'll close this one, as a "no go" unless you've got a suggestion to a solution ...
