### ISSUE TITLE
Capture leads and send email

### ISSUE THREAD

**Issue by amenk** [polterguy/magic#221]
**Is your feature request related to a problem? Please describe.**

When chatting with the the bot it would be nice to capture leads (eMail, Name)

**Describe the solution you'd like**

The bot should ask for Name and eMail and send an email via API (for example) to the customer service.

**Describe alternatives you've considered**

Link to contact form.

**Additional context**
Other bots like Intercom do something like that.

**Comment by polterguy** [comment]
Hi mate, it does this exact thing now. If you ask for instance _"Can I speak to a human"_ or _"how do I contact you"_ it will ask the user to drop his name and email into the prompt, and shot an email to whatever lead generation email address you've configured, or registered with ...

**Comment by amenk** [comment]
Awesome, will try

**Comment by polterguy** [comment]
Obviously not your real email address ... ;)

However, if you send us an email at team@ainiro.io we'd love to talk to you :)

<img width="802" alt="Screenshot 2023-06-30 at 4 38 29 PM" src="https://github.com/polterguy/magic/assets/8466933/e7571045-e5f3-4ed9-864d-30e15596d702">

**Comment by amenk** [comment]
In which commit was this implemented? I updated our docker test setup (docker compose pull, docker compose restart), configured the email settings, but the bot does not recognize was to contact :-)
