### ISSUE TITLE
page

### ISSUE THREAD

**Issue by wurangbo** [polterguy/magic#37]
hi guys,
    How can I define a pageable interface like "/api/controller?page=1&size=50"

**Comment by polterguy** [comment]
Hi there Wurangbo,

You actually get this out of the box as you choose the Crudify menu item, and crudify your table(s). If you look at the endpoints after you've crudified one or more of your tables, you will see that the `get` endpoint for your table optionally handles the `limit` and `offset` arguments. These are the equivalent of `page` and `size`.

Mapping goes like the following here ...

* `limit` == `size`
* `offset` == `page`

Except for one detail, it's not _"page"_, but rather _"number of records to skip"_. If you wish to calculate it from _"page"_, then multiply your page by the size of your `limit`, and you've got a _"page"_ equivalent.

Let me know if this fixes your problem :)

**Comment by polterguy** [comment]
I am going to close this one. For the record, if you use the Crudifier, you get paging _"for free"_ on your database tables ...
