### ISSUE TITLE
Getting types from assemblies

### ISSUE THREAD

**Issue by Sergey-Nosov-GH** [polterguy/magic#6]
In a few places throughout the code, while configuring services, there are calls like the following:

```csharp
AppDomain.CurrentDomain.GetAssemblies()
                .SelectMany(s => s.GetTypes())
```
If I understand the intention correctly, you do not want types from all of the domain assemblies, perhaps limiting the call to your assemblies only is needed. Maybe something like this, instead:

```csharp
AppDomain.CurrentDomain.GetAssemblies()
                .Where(a => a.FullName.Contains("magic."))
                .SelectMany(s => s.GetTypes())
```
HTH

**Comment by polterguy** [comment]
Thank you Sergey, and you are right - However, I anticipate that others might use different assembly names and namespaces when consuming this, so although it's an optimisation and also an improvement - It would also potentially create future problems.

This code is only executed during startup of the web app also, hence it has no runtime overhead, beyond maybe an additional 0.5 seconds of startup time for the web app - Which in an average solution should only normally occur once every two weeks to 2 years, depending upon your deployment routines.

So although it could improve startup time for the web app, it would also create problems for people creating their own modules, with different namespaces ...
